customer/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings


app_name='customer'


urlpatterns = [
    path('board',views.BoardView.as_view(),name='board_view'),
    path('register',views.RegisterView.as_view(),name='register_view'),
    path('landing',views.LandingView.as_view(),name='landing_view'),
    path('prodreg',views.ProdRegView.as_view(),name = 'prodreg_view'),
    path('products',views.ProductView.as_view(),name='products_view'),
    path('cart',views.CartView.as_view(),name='cart_view')
]

urlpatterns += staticfiles_urlpatterns()

customer/templates/warehouse/NeoSGP_home.html
<!DOCTYPE html>
<html>
<head>
<title>Sweet Guilty Pleasures</title>

<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
{% load static %}
    <link rel = "stylesheet" type="text/css" href="{% static 'css/Staple.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Home.css' %}">
<script>
function showTxt(){
	document.getElementById("txt").innerHTML = "Service code encoded, please choose among our available products.";
}
</script>
</head>

<body>
	<div class="bg pink">
	<h1 id="intro" class="shadow p-10 mb-10" style="margin-top:125px;">Welcome to Sweet Guilty Pleasures Cebu</h1><!-- placeimage here -->
  
<!-- The flexible grid (content) -->
<div class="container-fluid">
<div class="row" >
  
	<div class="col-lg-6" style="background-color:rgba(255,255,255,0.6);">
    
		<img src="/static/img/SGPlogo.jpg" alt="SGPlogo" style="width:400px;" id="lugo">
	</div>
	<div class="col-lg-6" style="background-color:rgba(255,255,255,0.6);">
		<form role="form" action="" method="POST" autocomplete="off" enctype="multipart/form-data">
      {% csrf_token %}
			<h4 class="shadow p-10 mb-10" style="background-color:#ff9999;margin:10px;border:5px solid;border-color:#ff3333;border-radius:15px;">Member's Access</h4>
			      <br><br>
            <center><button  id="custom" name="custom" type="submit" style="background-color:#f18973; width:30%; border-color:#f18973" class="btn btn-success btn-block" width="20px"> Customer Registration</button> </center>
            <br><br>
            <center><button  id="produkto" name="produkto" type="submit" style="background-color:#f18973; width:30%; border-color:#f18973" class="btn btn-success btn-block" width="20px"> Product Registration</button> </center>
            <br><br>
            <center><button  id="Browse" name="Browse" type="submit" style="background-color:#f18973; width:30%; border-color:#f18973" class="btn btn-success btn-block" width="20px"> Browse</button> </center>
    </form>
	

<!-- The flexible grid (content) -->

	
  <button type='button' class='btn btn-default btn-lg' id='myAbtUsBtn' style="background-color:#ff9999;margin:10px;border:5px solid;border-color:#ff3333;border-radius:15px;margin:50px;">About Us</button>
  <button type='button' class='btn btn-default btn-lg' id='myCntctUsBtn' style="background-color:#ff9999;margin:10px;border:5px solid;border-color:#ff3333;border-radius:15px;margin-left:250px;">Contact Us</button>
                  
                  
                    <!-- Modal for Log in-->
    <div class='modal fade' id='myAbtUsModal' role='dialog'>
      <div class='modal-dialog modal-lg'>
              
                        <!-- Modal content-->
        <div class='modal-content'>
          <div class='modal-header' style='padding:35px 50px;'>
            <h4 align="center">ABOUT US</h4>
              <button type='button' class='close' data-dismiss='modal'>&times;</button>
          </div>
          <div class='modal-body' style='padding:40px 50px;'>
            <div class="container-fluid">
              <div class="row">
            <div class="col-lg-6" style="background-color:rgba(255,255,255,0.6);">
            <h2>About the Shop</h2>
            <p style="text-align:justify;"> Sweet Guilty Pleasures started out as a small dream by the <i>"Petit Chef"</i>, Fae Therese C. Del Rosario,
            after watching her grandmother's blooming Fresh Lumpia business. And from that dream, grew a desire to make it come true. After two years of training from an international culinary school,
            </p>
            <p style="text-align:justify;"> Sweet Guilty Pleasures Cebu has made its name, both online and on Cebu's culinary market. With a wide array of pastries for you to customize, we promise to offer you sweets that are too good to resist, both for the eyes, and the appetite.</p>
  <figure>
    <div>
      
      <img src="/static/img/Achieve.png" alt="News_feature" style="display:block;margin-left:auto;margin-right:auto;">
    </div>
    <figcaption style="text-align:center;"><i>Sweet Guilty Pleasures being featured in Maayong Buntag Kapamilya</i></figcaption>
  </figure>
</div>
<div class="col-lg-6" style="background-color:rgba(255,255,255,0.6);border-color:#ff9999;border-width:medium;">
  <h2>The Mission</h2>
    <p style="font-size:30px;"><i>"To provide attractive and delicious treats to customers and pets, with the best quality."</i></p>
    <br>
    <h2>The Vision</h2>
    <p style="font-size:30px;"><i>"Provide treats and sweets that are edible and delightful for anyone and everyone."</i></p>
    
  </div>
</div>
</div>
        </div>
        <div class='modal-footer'>
                            
        <p>Not a member? <a href='#' id='insta-sign'>Sign Up</a></p>
       
          </div>
      </div>
                </div>
              </div>
      <div class='modal fade' id='myCntctUsModal' role='dialog'>
        <div class='modal-dialog'>
          <div class='modal-content'>
            <div class='modal-header' style='padding:35px 50px;'>
              <h4 align="center">Contacts</h4>
                <button type='button' class='close' data-dismiss='modal'>&times;</button>
            </div>
          <div class='modal-body' style='padding:40px 50px;'>
            <div class="container-fluid">
              <div class="row">
                <a href="https://www.facebook.com/sweetgpcebu"><h5>Visit our official facebook page!</h5></a>
              </div>
            </div>
          </div>
          <div class='modal-footer'>
                            
        <p>Other contact details are exclusive to members. <a href='#' id='insta-sign'>Sign Up Now!</a></p>
       
          </div>
        </div>
      </div>
    </div>
              
                  <script>
                  $(document).ready(function(){
                    $('#myAbtUsBtn').click(function(){
                      $('#myAbtUsModal').modal();
                    });
                  });
                  </script>
                  <script>
                  $(document).ready(function(){
                    $('#insta-sign').click(function(){
                      $('#myCntctUsModal').modal();
                      $('#myAbtUsModal').modal('toggle');
                    });
                  });
                  </script>
                  <script>
                  $(document).ready(function(){
                    $('#logback').click(function(){
                      $('#myAbtUsModal').modal();
                    $('#myCntctUsModal').modal('toggle');
                    });
                  });
                  </script>
                  <script>
                      $(document).ready(function(){
                        $('#myCntctUsBtn').click(function(){
                          $('#myCntctUsModal').modal();
                        });
                      });
                  </script>
</div>
</div>
</div>
<footer><h1> Vince Xavier C. del Rosario <h1></footer>
</div>

</body>

</html>

customer/templates/warehouse/Products.html
<!DOCTYPE html>
<html>
<head>
<title>Sweet Guilty Pleasures</title>

<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.css">
        <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.js"></script>
{% load static %}
    <link rel = "stylesheet" type="text/css" href="{% static 'css/Staple.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Home.css' %}">
<script>
function showTxt(){
  document.getElementById("txt").innerHTML = "Service code encoded, please choose among our available products.";
}
</script>
<script>

</script>
</head>

<body>
<div class="bg pink">

<br>
<nav class="navbar navbar-expand-lg navbar-dark shadow p-10 mb-10" role="navigation" style="background-color:#ff3333;border:5px solid pink">

    <a class="navbar-brand" href="SGP_home.html">
    <img src="/static/img/SGPlogo.jpg" alt="SGPlogo" style="width:85px;" id="lugo">
    </a>
	
      <h1 ><strong>Sweet Guilty Pleasures Cebu</strong></h1>
	
		<span class="navbar-toggler-icon"></span>
      

    </li>
	</ul>
  <!-- Trigger the modal with a button -->
<form role="form" action="" method="POST" autocomplete="off" enctype="multipart/form-data">
      {% csrf_token %}
 <button id="gotocart" name="gotocart" type="submit" class="btn btn-default btn-lg" > Cart</button>
</form>
<form role="form" action="" method="POST" autocomplete="off" enctype="multipart/form-data">
        {% csrf_token %}
        <button class="btn btn-default btn-lg" type="submit" id="gohome" name="gohome" href="{% url 'customer:landing_view' %}">Home</button>
</form>

<div class="modal fade" id="cartModal" role="dialog">
    <div class="modal-dialog">
     
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header" style="padding:35px 50px;">
          <h3 align="left">Cart</h3>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
              
                <div class="modal-body">
                  




</nav>

<br>

<h2 style="margin-top:150px;">Products</h2>
<div class="container-fluid" style="background-color:rgb(255, 255, 255,0.9);z-index:5;">
  <div class="row">
 {% for product in products %}

    <div class="col-lg-4" ><center>
      {% if product.picture.url is not null %}
<img src="{{product.picture.url}}" class="rounded-circle" width="300px" height="300px"alt="Tart Cake">
{% else %}
<img src="" class="rounded-circle" width="300px" height="300px"alt="Tart Cake">
{% endif %}
<br><br>
<p class="productname Food-Delivery" style="width:30%;" >{{product.name}}</p>
<p class="prices Food-Delivery" style="width:50%;" >Dollaps {{product.price}}.00 </p>
<p>by Dozen: {{product.byDozen}}</p>
<form id="form" role="form" action="" method="POST" autocomplete= "off" enctype="multipart/form-data" 
  background-color:white; style="width:75%; background-color:rgba(255,255,255,0.6); ">
  {% csrf_token %}
  <input type="text" name="product-name" value = {{product.name}} hidden>
  <input type="number" name="product-proice" value = {{product.price}} hidden>
<center> Quantity:
 <input id="prodname" name="quantity" type="number" required="required" class="form-control validate" >
 <button type="submit" id = "addtocart" name = "addtocart" onclick="showTxt()">Order</button></center>
 <p id="txt">Enter How many you want to order</p>

</form>
</center>

</div>
{% endfor %}


</div><!--row-->
</div><!--container-fluid-->
</div>
<footer class="shadow p-10 mb-10">
	<h2>Sweet Guilty Pleasures Cebu</h2>
	<p>All rights reserved</p>
	<p><a href="#top">Return to top</a></p>
</footer>
</div>
</body>
</html>

customer/templates/warehouse/cart.html
<!DOCTYPE html>
<html>
    <head>
        <title>Cart</title>

        <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
          <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
          <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.css">
        <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.js"></script>

        {% load static %}
        <link rel = "stylesheet" type="text/css" href="{% static 'css/Staple.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/Home.css' %}">
        <script>
            function showTxt(){
                document.getElementById("txt").innerHTML = "Service code encoded, please choose among our available products.";
            }
        </script>
    </head>

    <body>
            <div class="bg pink">
            <h1 id="intro" class="shadow p-10 mb-10" style="margin-top:125px;">Orders</h1><!-- placeimage here -->


        <!-- The flexible grid (content) -->
        <div class="container-fluid">
        <div class="row">
            
          <div class="col-lg-12" style="background-color:rgba(255,255,255,0.6);">
            
        <div align="center">
        <br><br>
        <form role="form" action="" method="POST" autocomplete="off" enctype="multipart/form-data">
        {% csrf_token %}
        <p align="right"><button><a type = "button" class="button button1" id="id_cart" href="{% url 'customer:products_view' %}" >Back to Browsing</a></button></p>
        </form>
        <form role="form" action="" method="POST" autocomplete="off" enctype="multipart/form-data">
        {% csrf_token %}
        <p align="right"><button><a type = "button" class="button button1" id="id_cart" href="{% url 'customer:landing_view' %}" >Home</a></button></p>
        </form>
                <table id="myTable" class="display table table-light" >
                  <thead>
                    <tr>
                      <th scope="col">Item Name</th>
                      <th scope="col">Price</th>
                      <th scope="col">Quantity</th>
                      <th scope="col">Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for items in orders %}
                    
                    <tr>
                        
                      <td>{{items.name}}</td>
                      <td>{{items.price}}</td>
                      <td>{{items.quantity}}</td>
                      {% if items.orderdate is null %}
                      <td>
                                <a type="button" class="btn btn-mdb-color btn-rounded" 
                                data-toggle="modal" data-target="#viewmodal-{{items.id}}" > Finalize </a>|

                                <a type="button" class="btn btn-mdb-color btn-rounded"
                                data-toggle="modal" data-target="#deletemodal-{{items.id}}" > Cancel Order</a>
                       </td>
                       {% else %}
                       <td>
                                Order Confirmed
                       </td>
                       {% endif %}

                    </tr>

                    <!-- View modal-->
                    <div class="modal fade" id="viewmodal-{{items.id}}" tabindex="2" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden ="false">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Order Details</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>                   
                                </div>
                                <form id="OrdahForm" method="post" >
                                {% csrf_token %}
                                <div class="modal-body">
                                    <input type="text" name="items-id" value = {{items.id}} hidden>
                                    <div class="form-group md-form font-weight-bold ">
                                        <label for="itemname" data-error="wrong" data-success="right">Name: </label>
                                        <input id="itemname" name="items-name" type="text" class="form-control" value="{{items.name}}" required="required" readonly>
                                    </div>

                                    <div class="form-group md-form font-weight-bold">
                                        <label for="itemprice" data-error="wrong" data-success="right">Price: </label>
                                        <input id="itemprice" name="items-price" type="number" class="form-control" 
                                        value="{{items.price}}" readonly>
                                    </div>

                                    <div class="form-group md-form font-weight-bold">
                                        <label for="itemquantity" data-error="wrong" data-success="right">Quantity: </label>
                                        <input id="itemquantity" name="items-quantity" type="number" class="form-control" 
                                        value="{{items.quantity}}"required="required">
                                    </div>
                                    <div class="form-group md-form font-weight-bold">
                                        <label for="orderDate" data-error="wrong" data-success="right">Date to be Delivered: </label>
                                        <input id="orderDate" name="orderdate" type="date" class="form-control" 
                                        required="required">
                                    </div> 
                                    <div class="form-group md-form font-weight-bold">
                                        <label for="orderLocation" data-error="wrong" data-success="right">Meetp-up Location: </label>
                                        <input id="orderLocation" name="location" type="text" class="form-control" 
                                        required="required">
                                    </div>                                   
                                </div>      
                                <div class="modal-footer">
                                        <input type="hidden" id="startup-id">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Back</button>
                                        <button type="submit" id = "conpirmOrder" name = "conpirmOrder" class="btn btn-secondary">Confirm</button>
                                </div>
                            </div>
                            </form>     
                        </div>
                    </div>
                        
                    
                    <!-- delete modal-->
        <div class="modal fade" id="deletemodal-{{items.id}}" tabindex="1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden ="false">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Cancel Order?</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>   
                                                
                    </div>
                    <form id="deleteForm" method="post" >
                    {% csrf_token %}
                    <div class="modal-body">
                        <input type="text" name="del-targetID" value = {{items.id}} hidden>
                        Are you sure about that?                        
                    </div>              
                    <div class="modal-footer">
                            <input type="hidden" id="startup-id">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                            <button type="submit" id = "cancelOrder" name = "cancelOrder" class="btn btn-secondary">Yes</button>
                    </div>
                </div>
                </form>
            </div>
        </div>

        {% endfor %}


        </tbody>
        </table>  

        </div>
        </div>

        </div>

        </div>

        


        <script>
                $(document).ready( function () {
                    $('#myTable').DataTable({
                            
                        });
                } );
        </script>
        



    </body>

</html>

customer/templates/warehouse/prodregis.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Product Registration</title>
  {% load static %}
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Google Fonts Roboto -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/css/bootstrap.min.css' %}">
  <!-- Material Design Bootstrap -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/css/mdb.min.css' %}">
  <!-- Your custom styles (optional) -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/css/style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/stepper.css' %}">
  
        <link rel = "stylesheet" type="text/css" href="{% static 'css/Staple.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/Home.css' %}">


</head>
<body class="bg">
<div>
  <!-- Start your project here-->
    
      <!-- Grid row -->
      {% block content %}
    <div class="row pt-5 d-flex flex-column justify-content-center align-items-center">
        <div class="col-md-7">

            <form id="form" role="form" action="" method="POST" autocomplete= "off" enctype="multipart/form-data">
                {% csrf_token %}

                <!-- First Step -->
                <div class="row setup-content-3" id="step-3">
                    <div class="col-md-12">
                        
                        <h3 class="font-weight-bold pl-0 my-4"><strong>Product Information</strong></h3>
                        <div class="form-group md-form font-weight-bold">
                            <strong>PRODUCT NAME:</strong>
                            <input id="prodname" name="name" type="text" required="required" class="form-control validate">
                        </div>
                        <div class="form-group md-form font-weight-bold">
                            <strong>Price (in Php): </strong>
                            <input id="prodprice" name="p_price" type="number" required="required" class="form-control validate" step="5">
                        </div>
                        <div class="form-group md-form font-weight-bold">
                            <strong>Sold by Dozen  </strong>
                            <input type="checkbox" name="p_isDoz" id="prodisDoz" value="Yes"><br>
                        </div>
                        <div class="form-group md-form font-weight-bold">
                          <strong>Product Picture  </strong>
                            <input type="file" name="prodPic" id="prodPic" style="width:50%" enctype="multipart/form-data">
                        </div>
                        
                        <button class="btn btn-mdb-color btn-rounded nextBtn-3 float-right" type="button">Next</button>
                        <button type ="submit" class="btn btn-success btn-rounded float-right">Submit</button>-->
                    </div>
                </div>
            </form>
      </div>
    </div>
    {% endblock content %}

  </div>
</body>
</html>